### ISSUE TITLE
The optimization procedure

### ISSUE THREAD

**Issue by IssamLaradji** [mauriziofilippone/deep_gp_random_features#2]
When do you terminate the optimization ? Do you use the validation set for early stopping ?

**Comment by remidomingues** [comment]
Hello Issam,

As you can see [here](https://github.com/mauriziofilippone/deep_gp_random_features/blob/master/code/dgp_rff.py#L366), the training ends when a given number of iterations is reached.
Of course, you can also monitor the evolution of the `nll_test` variable from [here](https://github.com/mauriziofilippone/deep_gp_random_features/blob/master/code/dgp_rff.py#L412) and add a breaking condition.

Cheers.
